import { Routes } from '@angular/router';
import { LoginComponent } from './pages/login/login.component';
import { HomeComponent } from './pages/home/home.component';
import { HotelListComponent } from './pages/hotel-list/hotel-list.component';
import { HotelDetailsComponent } from './pages/hotel-details/hotel-details.component';
import { WelcomePageComponent } from './pages/welcome-page/welcome-page.component';
import { IntegrationsComponent } from './pages/integrations/integrations.component';
import { RoleListeComponent } from './pages/role-liste/role-liste.component';
import { RoleDetailsComponent } from './pages/role-details/role-details.component';
import { UserListComponent } from './pages/user/user.component';
import { UserDetailsComponent } from './pages/user-details/user-details.component';
import { CheckInComponent } from './pages/check-in/check-in.component';
import { ClientReservationComponent } from './pages/client-reservation/client-reservation.component';
import { ClientListComponent } from './pages/client-list/client-list.component';

export const appRoutes: Routes = [
  { path: '', component: WelcomePageComponent },
  { path: 'login', component: LoginComponent },
  { path: 'home', component: HomeComponent },
  { path: 'hotels', component: HotelListComponent },
  { path: 'hotel-details', component: HotelDetailsComponent },
  { path: 'clients', component: ClientListComponent },
  { path: 'client-reservation/:id', component: ClientReservationComponent },
  { path: 'Marketplace', component: IntegrationsComponent },
  { path: 'role', component: RoleListeComponent },
  { path: 'role-details', component: RoleDetailsComponent },
  { path: 'user', component: UserListComponent },
  { path: 'user-details/:id', component: UserDetailsComponent },
  { path: 'reservations', component: CheckInComponent },
];
